"""A small, dependency-free Tetris environment with a gymnasium-style API,
sized down (6 wide x 12 tall) to keep per-tick simulation cost tractable for
the spiking-network reservoir driving it.

reset() -> obs
step(action) -> obs, reward, done, info

obs is a (HEIGHT, WIDTH) uint8 numpy array: 0 = empty, 1-7 = occupied by that
piece type (see PIECE_INDEX), so a GUI can color-code locked blocks by piece.
Any nonzero value is still simply "occupied" for encoding/training purposes.
Actions: 0=noop, 1=left, 2=right, 3=rotate, 4=soft_drop
"""
from __future__ import annotations

import numpy as np

WIDTH = 6
HEIGHT = 12

ACTION_NOOP = 0
ACTION_LEFT = 1
ACTION_RIGHT = 2
ACTION_ROTATE = 3
ACTION_DROP = 4
N_ACTIONS = 5

# Standard tetromino shapes as lists of (row, col) offsets, one rotation state
# to start; additional rotation states generated by 90-degree rotation.
_BASE_SHAPES = {
    "I": [(0, 0), (0, 1), (0, 2), (0, 3)],
    "O": [(0, 0), (0, 1), (1, 0), (1, 1)],
    "T": [(0, 0), (0, 1), (0, 2), (1, 1)],
    "S": [(1, 0), (1, 1), (0, 1), (0, 2)],
    "Z": [(0, 0), (0, 1), (1, 1), (1, 2)],
    "J": [(0, 0), (1, 0), (1, 1), (1, 2)],
    "L": [(0, 2), (1, 0), (1, 1), (1, 2)],
}


def _rotate_cells(cells):
    """Rotate a set of (row, col) cells 90 degrees clockwise about the origin,
    then normalize so min row/col are 0."""
    rotated = [(c, -r) for r, c in cells]
    min_r = min(r for r, c in rotated)
    min_c = min(c for r, c in rotated)
    return [(r - min_r, c - min_c) for r, c in rotated]


def _all_rotations(cells):
    rotations = [cells]
    cur = cells
    for _ in range(3):
        cur = _rotate_cells(cur)
        rotations.append(cur)
    return rotations


_SHAPE_ROTATIONS = {name: _all_rotations(cells) for name, cells in _BASE_SHAPES.items()}
_SHAPE_NAMES = list(_SHAPE_ROTATIONS.keys())

# Nonzero board-cell values so a GUI can color-code locked blocks by piece.
PIECE_INDEX = {name: i + 1 for i, name in enumerate(_SHAPE_NAMES)}
INDEX_TO_PIECE = {v: k for k, v in PIECE_INDEX.items()}

# Public alias so a GUI can draw a next-piece preview using each shape's
# base (rotation 0) cell layout, without reaching into a private name.
PIECE_SHAPES = _BASE_SHAPES


class TetrisEnv:
    def __init__(self, width: int = WIDTH, height: int = HEIGHT, seed: int | None = None):
        self.width = width
        self.height = height
        self.rng = np.random.default_rng(seed)
        self.board = None
        self.piece_name = None
        self.next_piece_name = None
        self.rotation_idx = None
        self.piece_row = None
        self.piece_col = None
        self.done = False
        self._last_lines = 0

    def reset(self):
        self.board = np.zeros((self.height, self.width), dtype=np.uint8)
        self.done = False
        self.next_piece_name = self._random_piece_name()
        self._spawn_piece()
        return self._obs()

    def _random_piece_name(self):
        return _SHAPE_NAMES[self.rng.integers(0, len(_SHAPE_NAMES))]

    def _spawn_piece(self):
        # One-piece lookahead: promote the previewed piece to current, then
        # draw a new one to preview. Lets the agent see what's coming next,
        # not just react to the piece already falling.
        self.piece_name = self.next_piece_name
        self.next_piece_name = self._random_piece_name()
        self.rotation_idx = 0
        cells = _SHAPE_ROTATIONS[self.piece_name][0]
        max_col = max(c for _, c in cells)
        self.piece_row = 0
        self.piece_col = (self.width - (max_col + 1)) // 2
        if self._collides(self.piece_row, self.piece_col, cells):
            self.done = True

    def _current_cells(self):
        return _SHAPE_ROTATIONS[self.piece_name][self.rotation_idx]

    def _collides(self, row, col, cells):
        for dr, dc in cells:
            r, c = row + dr, col + dc
            if c < 0 or c >= self.width or r >= self.height:
                return True
            if r >= 0 and self.board[r, c]:
                return True
        return False

    def step(self, action: int):
        if self.done:
            return self._obs(), 0.0, True, {}

        reward = 0.0
        cells = self._current_cells()

        if action == ACTION_LEFT:
            if not self._collides(self.piece_row, self.piece_col - 1, cells):
                self.piece_col -= 1
        elif action == ACTION_RIGHT:
            if not self._collides(self.piece_row, self.piece_col + 1, cells):
                self.piece_col += 1
        elif action == ACTION_ROTATE:
            n_rot = len(_SHAPE_ROTATIONS[self.piece_name])
            new_idx = (self.rotation_idx + 1) % n_rot
            new_cells = _SHAPE_ROTATIONS[self.piece_name][new_idx]
            if not self._collides(self.piece_row, self.piece_col, new_cells):
                self.rotation_idx = new_idx
        # ACTION_DROP and ACTION_NOOP fall through to gravity below;
        # DROP just means "no horizontal move this tick", gravity still applies
        # once per tick either way (soft drop rather than hard drop, to keep the
        # step/tick semantics uniform for the spiking-network decision loop).

        cells = self._current_cells()
        if not self._collides(self.piece_row + 1, self.piece_col, cells):
            self.piece_row += 1
        else:
            self._lock_piece(cells)
            lines_cleared = self._clear_lines()
            reward += self._line_clear_reward(lines_cleared)
            self._spawn_piece()
            if self.done:
                reward -= 1.0  # topped out

        reward += 0.01  # small per-tick survival reward
        stack_height = self._stack_height()
        reward -= 0.001 * stack_height  # discourage tall, precarious stacks

        return self._obs(), reward, self.done, {"lines_cleared_this_tick": self._last_lines}

    def _lock_piece(self, cells):
        piece_idx = PIECE_INDEX[self.piece_name]
        for dr, dc in cells:
            r, c = self.piece_row + dr, self.piece_col + dc
            if 0 <= r < self.height and 0 <= c < self.width:
                self.board[r, c] = piece_idx

    def _clear_lines(self):
        full_rows = [r for r in range(self.height) if self.board[r].all()]
        if not full_rows:
            self._last_lines = 0
            return 0
        keep_rows = [r for r in range(self.height) if r not in full_rows]
        new_board = np.zeros_like(self.board)
        new_board[len(full_rows):, :] = self.board[keep_rows, :]
        self.board = new_board
        self._last_lines = len(full_rows)
        return len(full_rows)

    @staticmethod
    def _line_clear_reward(n_lines: int) -> float:
        # Nonlinear bonus rewards clearing multiple lines at once, matching
        # standard Tetris scoring intuition (single/double/triple/tetris).
        return {0: 0.0, 1: 1.0, 2: 3.0, 3: 5.0, 4: 8.0}.get(n_lines, 8.0)

    def _stack_height(self) -> int:
        occupied_rows = np.where(self.board.any(axis=1))[0]
        if len(occupied_rows) == 0:
            return 0
        return self.height - occupied_rows.min()

    def _obs(self):
        obs = self.board.copy()
        cells = self._current_cells() if not self.done else []
        piece_idx = PIECE_INDEX[self.piece_name] if self.piece_name else 0
        for dr, dc in cells:
            r, c = self.piece_row + dr, self.piece_col + dc
            if 0 <= r < self.height and 0 <= c < self.width:
                obs[r, c] = piece_idx
        return obs

    def render_ascii(self) -> str:
        obs = self._obs()
        lines = []
        for row in obs:
            lines.append("".join(INDEX_TO_PIECE.get(v, ".")[0] if v else "." for v in row))
        return "\n".join(lines)
